"""Generate JSON Schema (and optionally TypeScript) from the Python contract.

    python -m evalvitals.contract.export --out docs/contract

Python stays the single source of truth; the schemas are build artifacts. Wire a
CI check that regenerates and fails on a diff, so a field added in Python can
never silently miss the frontend.

TypeScript is generated here too (``contract.d.ts``), in Python — see
:mod:`evalvitals.contract.typescript` for why not npx.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from evalvitals.contract import SCHEMA_VERSION, STAGE_IO


def export(out_dir: Path, *, typescript: bool = True, frontend: bool = True) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    schemas: dict[str, dict] = {}
    for stage, contract in STAGE_IO.items():
        for role, model in (("Input", contract.input), ("Output", contract.output)):
            schema = model.model_json_schema(mode="serialization")
            schemas[f"{stage}.{model.__name__}"] = schema
            schema["$id"] = f"https://evalvitals.dev/contract/{stage}.{model.__name__}.json"
            schema["x-stage"] = stage
            schema["x-role"] = role.lower()
            schema["x-schema-version"] = SCHEMA_VERSION
            schema["x-optional-stage"] = contract.optional
            path = out_dir / f"{stage}.{model.__name__}.schema.json"
            path.write_text(json.dumps(schema, indent=2, ensure_ascii=False) + "\n")
            written.append(path)

    index = {
        "schema_version": SCHEMA_VERSION,
        "stages": [
            {
                "stage": s,
                "purpose": c.purpose,
                "optional": c.optional,
                "input": f"{s}.{c.input.__name__}.schema.json",
                "output": f"{s}.{c.output.__name__}.schema.json",
            }
            for s, c in STAGE_IO.items()
        ],
    }
    idx = out_dir / "index.json"
    idx.write_text(json.dumps(index, indent=2, ensure_ascii=False) + "\n")
    written.append(idx)

    readme = out_dir / "README.md"
    readme.write_text(_layout_doc())
    written.append(readme)

    if typescript:
        from typing import get_args

        from evalvitals.contract.common import MEDIA_SLOTS, Modality
        from evalvitals.contract.typescript import render

        rendered = render(
            schemas, schema_version=SCHEMA_VERSION,
            aliases={"Modality": get_args(Modality), "MediaSlot": MEDIA_SLOTS},
        )
        targets = [out_dir / "contract.d.ts"]
        if frontend:
            targets += _frontend_targets()
        for ts in targets:
            ts.parent.mkdir(parents=True, exist_ok=True)
            ts.write_text(rendered)
            written.append(ts)
    return written


def _frontend_targets() -> "list[Path]":
    """Where else the declaration file has to land.

    The report UI imports these types, so it needs the file inside its own
    ``src/``. Writing it from here — rather than copying it in by hand — is what
    keeps the two from drifting: one command regenerates both, and ``--check``
    fails on either being stale. A vendored copy nobody regenerates is worse
    than no types at all, because it looks authoritative while being wrong.
    """
    web = Path(__file__).resolve().parents[1] / "reporting" / "web" / "src" / "contract"
    return [web / "contract.d.ts"] if web.parent.parent.is_dir() else []


def _layout_doc() -> str:
    """Describe what a finished run puts on disk, generated from STAGE_IO.

    Written rather than hand-maintained because the thing it documents — which
    stages exist, what each emits, which are optional — is already data. A prose
    copy would be one more thing to drift, which is the failure this whole
    package exists to prevent.
    """
    from evalvitals.contract.emit import CONTRACT_DIR, STAGE_WIRE

    lines = [
        "<!-- GENERATED by `python -m evalvitals.contract.export`. Do not edit. -->",
        "# What an M1-M5 run puts on disk",
        "",
        f"Schema version **{SCHEMA_VERSION}**. Bumped only when a field's *meaning*",
        "changes — adding a field is additive and does not bump it, so a reader must",
        "**ignore unknown fields, never reject them**.",
        "",
        "## Layout",
        "",
        "```text",
        "<run>/",
        f"├── {CONTRACT_DIR}/                  ← the typed source of truth",
        "│   ├── index.json            every payload, its stage, cycle and wire type",
        "│   ├── c0.m1.json            one file per (cycle, stage)",
        "│   ├── c0.m2.json",
        "│   ├── c0.m3.json",
        "│   ├── c-1.m5.json           cycle -1 = the post-loop / held-out pass",
        "│   ├── m4_fix.json           post-loop stages carry no cycle prefix",
        "│   └── <stage>.invalid.json  a payload that FAILED validation, with the error",
        "├── run_log.jsonl             the raw event stream (untyped; predates this)",
        "├── artifacts/",
        "│   ├── case_media/           the media each case was evaluated on",
        "│   └── *.npy, *.json         heavy arrays, referenced by path, never inlined",
        "├── report/                   human deliverables",
        "└── figures/                  M1 heatmaps, M2 effect plots",
        "```",
        "",
        "**The run carries its own data.** Media a case was evaluated on is copied",
        "into `artifacts/case_media/`, and every `MediaRef` path is relative to the",
        "run root. A run pointing at the dataset where the producing machine kept",
        "it would be readable only on that machine — and the normal way these are",
        "read is zipped, moved, opened somewhere else. So the archive is the",
        "evidence, complete, and needs nothing mounted beside it.",
        "",
        "That costs size: the Music-AVQA audio-visual run is 145 KB without its",
        "media and 162 MB with it. It is the right trade — a diagnosis whose",
        "evidence has gone missing is not a diagnosis. Strip the media only for a",
        "reader that wants the numbers alone, and know that is what you did.",
        "",
        "The file name is `c<cycle>.<stage>.json`. A stage that runs once after the",
        "loop has no cycle prefix. `<stage>.invalid.json` means that stage produced",
        "something the contract rejected: show it as broken, never as absent.",
        "",
        "## Stages",
        "",
        "| Stage | Emits | What it is for | Optional |",
        "|---|---|---|---|",
    ]
    for stage, c in STAGE_IO.items():
        wire = STAGE_WIRE.get(stage, c.output.__name__)
        lines.append(f"| `{stage}` | [`{wire}`]({stage}.{c.output.__name__}.schema.json) "
                     f"| {c.purpose} | {'yes' if c.optional else 'no'} |")
    lines += [
        "",
        "Execution order is not the numbering: the loop runs M1→M2→M3→M5 as its cycle",
        "and calls M4 once afterwards, because a repair should only be attempted on a",
        "hypothesis M5 verified.",
        "",
        "## Reading it",
        "",
        "```ts",
        'import type { ProbeOutput, DiagnosisOutput } from "./contract";',
        "",
        'const index = await (await fetch("contract/index.json")).json();',
        "for (const p of index.payloads) {",
        "  const payload = await (await fetch(`contract/${p.file}`)).json();",
        "  // p.stage, p.cycle and p.wire say what you just loaded.",
        "}",
        "```",
        "",
        "Four distinctions the payloads encode, which a reader must not collapse:",
        "",
        "- **Absent, null, empty, zero and false are five different things.** Every",
        "  optional field is explicitly nullable. `ungrounded_rate_audio: null` means no",
        "  case carried audio; `0.0` means every case that did stayed grounded.",
        "- **`status.state` separates outcomes that look alike.** `empty` and",
        "  `abstained` are successes with nothing to show; `failed` and `unavailable`",
        "  are not; `partial` means some of it arrived. Rendering them identically",
        "  destroys the only signal for whether to trust an absence.",
        "- **Modality is a set of slots, never a model-kind label.** LLM / VLM / ALM /",
        "  AVLM are four subsets of `{text, image, audio, video}`. `AnalyzerSelection`",
        "  carries what the model accepts, what the cases filled, and what analyzer",
        "  routing actually used — they differ, and the difference is diagnostic.",
        "- **A hypothesis with an empty `test_design` is undecidable.** It will return",
        "  INCONCLUSIVE on every cycle no matter how much evidence is gathered. Join",
        "  M5's `hypothesis_id` back to M3 before reading any verdict.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=Path("docs/contract"))
    ap.add_argument("--no-typescript", action="store_true", help="JSON Schema only.")
    ap.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if any output differs from what is on disk. For CI: a "
             "generated artifact nothing verifies is a stale artifact.",
    )
    args = ap.parse_args()

    if args.check:
        import tempfile

        # frontend=False: a check must not write into the tree it is checking,
        # or the second run always passes.
        with tempfile.TemporaryDirectory() as tmp:
            fresh = export(Path(tmp), typescript=not args.no_typescript, frontend=False)
            stale = []
            for f in fresh:
                targets = [args.out / f.name]
                if f.name == "contract.d.ts":
                    targets += _frontend_targets()
                for target in targets:
                    if not target.exists() or target.read_text() != f.read_text():
                        stale.append(str(target))
        if stale:
            raise SystemExit(
                "contract artifacts are out of date: " + ", ".join(sorted(stale))
                + f"\nregenerate with: python -m evalvitals.contract.export --out {args.out}"
            )
        print(f"{args.out}: up to date")
        return

    for p in export(args.out, typescript=not args.no_typescript):
        print(p)


if __name__ == "__main__":
    main()
