"""JSON Schema -> TypeScript for the stage contract.

Written in Python on purpose. ``export.py`` documented ``npx
json-schema-to-typescript`` as the way to get types, which puts a node toolchain
and a network fetch between a Python field and the frontend that has to decode
it — and a generation step that can fail for reasons unrelated to the contract
is a generation step CI will end up skipping. One language, one command, one
committed artifact that a diff check can police.

The output is a single ``.d.ts``: every stage's payload and every type it
references, so a frontend imports one file and gets the whole pipeline.
"""

from __future__ import annotations

from typing import Any

_SCALARS = {
    "string": "string", "integer": "number", "number": "number",
    "boolean": "boolean", "null": "null",
}


def _ts_type(schema: dict[str, Any]) -> str:
    """One JSON-Schema node as a TypeScript type expression."""
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(v) for v in schema["enum"]) or "never"
    for key in ("anyOf", "oneOf"):
        if key in schema:
            parts = [_ts_type(s) for s in schema[key]]
            # dict.fromkeys, not set: a stable union order keeps the generated
            # file diffable, and a diff check is the only thing that makes a
            # generated artifact trustworthy.
            return " | ".join(dict.fromkeys(parts)) or "unknown"
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return _ts_type(schema["allOf"][0])

    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(dict.fromkeys(_SCALARS.get(k, "unknown") for k in kind))
    if kind == "array":
        items = schema.get("items") or schema.get("prefixItems")
        if isinstance(items, list):   # tuple, e.g. ci: (float, float)
            return "[" + ", ".join(_ts_type(i) for i in items) + "]"
        return f"({_ts_type(items or {})})[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        value = _ts_type(extra) if isinstance(extra, dict) else "unknown"
        return f"{{ [key: string]: {value} }}"
    return _SCALARS.get(kind, "unknown")


def _literal(value: Any) -> str:
    if isinstance(value, str):
        return '"' + value.replace('"', '\\"') + '"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def _doc(schema: dict[str, Any], indent: str) -> str:
    """Carry the Python docstring/description across. A generated type with no
    prose sends the reader back to the Python file, which is the drift this
    whole contract exists to avoid."""
    text = (schema.get("description") or "").strip()
    if not text:
        return ""
    lines = [ln.rstrip() for ln in text.splitlines()]
    body = "\n".join(f"{indent} * {ln}".rstrip() for ln in lines)
    return f"{indent}/**\n{body}\n{indent} */\n"


def _interface(name: str, schema: dict[str, Any]) -> str:
    if "enum" in schema and "properties" not in schema:
        return f"{_doc(schema, '')}export type {name} = {_ts_type(schema)};\n"
    props = schema.get("properties") or {}
    required = set(schema.get("required") or ())
    out = [_doc(schema, ""), f"export interface {name} {{\n"]
    for field, sub in props.items():
        opt = "" if field in required else "?"
        out.append(_doc(sub, "  "))
        out.append(f"  {field}{opt}: {_ts_type(sub)};\n")
    if schema.get("additionalProperties") is True:
        out.append(
            "  /** Producer-defined keys. The envelope is closed; payload areas are not. */\n"
            "  [key: string]: unknown;\n"
        )
    out.append("}\n")
    return "".join(out)


def render(
    schemas: dict[str, dict[str, Any]], *, schema_version: int,
    aliases: "dict[str, tuple[Any, ...]] | None" = None,
) -> str:
    """Render every stage schema plus its ``$defs`` into one declaration file.

    ``aliases`` names literal unions that pydantic inlines at every use site
    (``Modality`` is one). A frontend that wants to write ``slot: Modality``
    cannot, unless the name survives generation — and passing them explicitly
    beats inferring which inline unions "look like" a named type.
    """
    defs: dict[str, dict[str, Any]] = {}
    roots: dict[str, dict[str, Any]] = {}
    for schema in schemas.values():
        for name, sub in (schema.get("$defs") or {}).items():
            defs.setdefault(name, sub)
        root = {k: v for k, v in schema.items() if k != "$defs"}
        roots.setdefault(root.get("title") or "Unnamed", root)

    parts = [
        "// GENERATED by `python -m evalrx.contract.export --out docs/contract`.\n"
        "// Do not edit: Python is the source of truth (evalrx/contract/).\n"
        f"// schema_version {schema_version}\n\n"
        "/** Bumped only when a field's MEANING changes. Unknown fields must be\n"
        " *  ignored by readers, never rejected. */\n"
        f"export const SCHEMA_VERSION = {schema_version};\n\n",
    ]
    for name, values in sorted((aliases or {}).items()):
        parts.append(
            f"export type {name} = " + " | ".join(_literal(v) for v in values) + ";\n\n"
        )
    for name in sorted(defs):
        if name in roots:
            continue
        parts.append(_interface(name, defs[name]) + "\n")
    for name in sorted(roots):
        parts.append(_interface(name, roots[name]) + "\n")
    return "".join(parts)


__all__ = ["render"]
