// GENERATED by `python -m evalrx.contract.export --out docs/contract`.
// Do not edit: Python is the source of truth (evalrx/contract/).
// schema_version 4

/** Bumped only when a field's MEANING changes. Unknown fields must be
 *  ignored by readers, never rejected. */
export const SCHEMA_VERSION = 4;

export type MediaSlot = "image" | "audio" | "video";

export type Modality = "text" | "image" | "audio" | "video";

/**
 * One threshold-rule violation. The no-judge baseline signal.
 */
export interface AnalysisFindingWire {
  analyzer: string;
  metric: string;
  value: number;
  threshold: number;
  direction: "above" | "below";
  severity: "high" | "medium" | "low";
  message: string;
}

/**
 * Which analyzers ran, and how they were chosen.
 *
 * Kept separate from the results so a reader can tell "not selected" from
 * "selected and produced nothing". The judge's per-analyzer reasoning is not
 * here — it is the response half of ``prompts/c<cycle>_m1_selection.*``.
 *
 * Modality is recorded as three related sets rather than one ``model_kind``
 * label. The label was a combination enum (``vlm`` / ``omni`` / ...), which is
 * what design rule 3 forbids: it has no member for an audio-visual model, and
 * "omni" collapses the one distinction routing depends on — an omni model
 * evaluated on an audio benchmark must be routed as audio, not as everything
 * it is capable of.
 */
export interface AnalyzerSelection {
  /**
   * What the model DECLARES it can consume (from its spec).
   */
  model_modalities?: ("text" | "image" | "audio" | "video")[];
  /**
   * What the case batch actually FILLS. Text is the floor, not a slot.
   */
  probed_modalities?: ("text" | "image" | "audio" | "video")[];
  /**
   * The slots routing actually used. Normally model ∩ probed; equal to model_modalities when the batch filled no media slot at all, because an empty batch is no evidence about what is under test. A reader comparing this with probed_modalities can see that fallback happened.
   */
  routed_on?: ("text" | "image" | "audio" | "video")[];
  /**
   * The BATCH carries agent trajectories. Orthogonal to modality — a VLM can drive a tool loop. NOT 'the model supports tool calls': every chat model served over an OpenAI-compatible endpoint declares that, so reading the capability here labelled a plain single-turn text run 'llm+agent' and told the reader trajectories were analysed when none existed. Ranking makes the same distinction — a declared capability never outranks the data.
   */
  is_agent?: boolean;
  selector?: "llm_judge" | "static_strategy" | "explicit";
  /**
   * Bespoke probes written when no standard analyzer covered the mode.
   */
  generated?: (string)[];
}

/**
 * A heavy artifact (``.npy``, ``.png``, workspace dir) left on disk.
 *
 * Heavy arrays never go inline: a browser must not parse a ``.npy``, and a
 * JSONL event must not carry an attention map.
 */
export interface ArtifactRef {
  /**
   * Relative to runRoot.
   */
  path: string;
  media_type?: "npy" | "png" | "jpg" | "json" | "text" | "dir" | "other";
  bytes?: number | null;
}

/**
 * A batch referenced by file rather than inlined (the normal case).
 */
export interface CaseBatchRef {
  path: string;
  n_cases: number;
  split?: "all" | "explore" | "confirm" | "discovery" | null;
}

/**
 * Family-level multiplicity control across every tested signal.
 *
 * Testing 40 signals at alpha=0.05 yields ~2 "significant" results from luck
 * alone. Without this the screen is not a screen.
 *
 * ``mixed-BH/e-BH`` is its own member rather than being folded into either
 * neighbour: it says the family contained both p-values and e-values, which
 * carry different validity guarantees, and a reader weighing the verdict needs
 * to know that the guarantee is the weaker of the two.
 */
export interface CorrectedRejections {
  method?: "e-BH" | "BH" | "mixed-BH/e-BH" | "none";
  alpha?: number;
  /**
   * True while the analysis phase withholds the verdict.
   */
  deferred?: boolean;
  n_tested?: number;
  /**
   * analysis_key values that survived. The source of truth.
   */
  rejected_result_keys?: (string)[];
}

/**
 * Strength tier of the deciding evidence.
 *
 * ``INTERVENTION`` beats ``OBSERVATIONAL``: a paired contrast changed one
 * variable and re-ran, so it carries causal weight an association does not.
 */
export type EvidenceGrade = "intervention" | "observational" | "none";

/**
 * Descriptive EDA notes from the optional explore side-path.
 *
 * Never authoritative. It enters the M3 prompt and the dashboard and nothing
 * else — not M2's tested family, not M5, not the fix gate. It shapes WHICH
 * hypotheses get proposed, never WHETHER one is true.
 */
export interface ExploreContextWire {
  observations?: (string)[];
  charts?: ({ [key: string]: unknown })[];
  caveats?: (string)[];
  source?: string;
  authoritative?: false;
}

/**
 * Pointer replacing an inline value that exceeded the size budget.
 *
 * Detect by shape (``kind == "external_ref"``), lazy-load ``path``, and keep
 * ``n_items`` visible while loading. Never render the pointer as one item.
 */
export interface ExternalRef {
  kind?: "external_ref";
  /**
   * Relative to runRoot. Never an absolute host path.
   */
  path: string;
  /**
   * Item count in the target, when countable.
   */
  n_items?: number | null;
  /**
   * Serialized size of the externalized value.
   */
  bytes: number;
}

/**
 * Analyzer-specific light payload. JSON-safe by construction.
 *
 * Two shapes are read by the pipeline and therefore named here; everything else
 * is free-form and passes through to the raw inspector.
 */
export interface FindingsWire {
  /**
   * One row per case. Empty is valid (a scalar-only analyzer).
   */
  per_case?: (PerCaseRow)[];
  /**
   * {strategy -> {case_id -> success}} for paired contrasts. This is what makes an INTERVENTION-grade verdict possible downstream.
   */
  by_strategy?: { [key: string]: { [key: string]: number } } | null;
  /** Producer-defined keys. The envelope is closed; payload areas are not. */
  [key: string]: unknown;
}

/**
 * One candidate validated against the unmodified baseline on the SAME cases.
 *
 * Every count here is a PAIRED flip, never a rate difference. "repaired 18 /
 * broke 1" is a statement about individual cases changing sign; a pass-rate
 * delta is not the same claim and must never be displayed as if it were.
 */
export interface FixAttemptWire {
  tier: "L0" | "L1" | "L2" | "L3a" | "L3b" | "L4";
  /**
   * The reader-facing identifier, e.g. `R3`. Assigned by the producer over the whole run and STABLE across `selection` and `attempted`, so a reader who sees R3 in the sweep can find R3's card and know it is the same repair.
   *
   * This exists because `name` cannot do the job. Consumers that numbered rows by list position gave the same repair two different numbers in the two lists, which is worse than no number at all. Empty means the producer assigned none; a consumer may then number by position, but only within one list and never as a cross-list identity.
   */
  ref?: string;
  /**
   * Machine slug, e.g. `audio_evidence_then_answer`. It is the JOIN KEY — `best`, `selected_on_explore` and `ebh_survivors` all name a candidate this way — and it is what the attempt folder on disk is called.
   *
   * It is NOT the label to show a reader. These slugs are chosen by the agent while naming its log files, so they read as identifiers rather than as language. Show `ref` to point at a candidate and `headline` to say what it does.
   */
  name: string;
  /**
   * One plain sentence saying what this repair changes, written for a reader with no background in the field: no tier names, no metric names, no jargon, no slug echoed back. "Ask the model to describe what it hears before answering" — not "audio-evidence-first prompt scaffold".
   *
   * Empty when the producer had nothing readable to offer, which a consumer should render as an honest blank rather than by humanising the slug: `audio_evidence_then_answer` -> "Audio Evidence Then Answer" invents fluency the run never had.
   */
  headline?: string;
  kind?: string | null;
  source?: string | null;
  /**
   * What this candidate DOES, as a graph plus a rendered draw.io diagram. The payload is the implementation; this is the explanation. Required for any candidate a reader is asked to accept — a repair nobody can follow cannot be reviewed, only trusted.
   */
  methodology?: MethodologyWire | null;
  /**
   * Self-contained attempt folder, RELATIVE TO THE RUN ROOT. Preferred join key across rounds — name alone is not unique.
   *
   * It holds `outputs.jsonl`, one line per validated case: `{case_id, status, output}` where status is fixed / broken / unchanged. That is what a reader needs to study a repair case by case — the candidate's actual answer beside the baseline's — and it is kept out of this payload because it is one row per case per candidate. Recorded relative because an absolute producer path resolves nowhere else, which is the same reason MediaRef paths are relative.
   */
  trial_root?: string | null;
  n_pairs?: number;
  n_baseline_correct?: number;
  n_fixed?: number;
  n_broken?: number;
  fixed_cases?: (string)[];
  broken_cases?: (string)[];
  /**
   * Cases the candidate actually touched.
   */
  n_applicable?: number;
  /**
   * applicable FAILs / total FAILs.
   */
  coverage?: number | null;
  /**
   * Dropped as baseline-unstable, so sampling noise is not read as regression.
   */
  n_unstable?: number;
  /**
   * Cases the scaffold solved by its own computation under frozen_model_control — excluded from the paired test rather than counted as fixed.
   */
  n_model_independent?: number;
  effect?: number | null;
  e_value?: number | null;
  /**
   * This candidate's own gate. Not sufficient to win.
   */
  reject?: boolean;
  /**
   * The candidate's outcome. Subsumes a separate `fixed` boolean (verdict == 'fixed') and a separate exec_error ('not_executed').
   */
  verdict: "fixed" | "partial" | "unsafe" | "regressed" | "no_effect" | "not_executed" | "model_independent";
  summary?: string;
}

export type HypothesisStatus = "proposed" | "testing" | "supported" | "refuted" | "inconclusive";

/**
 * One hypothesis's verdict.
 *
 * ``effect_size`` is signal-group minus control-group fail rate, so its SIGN is
 * the verdict's direction: positive supports the claim, negative refutes it.
 * A refutation is a real, useful outcome — not a failure to conclude.
 */
export interface HypothesisTestResultWire {
  /**
   * Points into the M3 DiagnosisOutput.
   */
  hypothesis_id: string;
  status: HypothesisStatus;
  /**
   * e.g. 'signal_label_assoc' / 'fail_rate_comparison'.
   */
  test_name: string;
  effect_size?: number | null;
  /**
   * Geometric mean of evidence gap, sample adequacy, control cleanliness.
   */
  confidence: number;
  evidence_grade?: EvidenceGrade;
  is_consistent_with_protocol: boolean;
  /**
   * One-line natural-language summary.
   */
  verdict: string;
  evidence?: TestEvidence;
}

/**
 * One falsifiable claim about *why* the model fails.
 *
 * ``statement`` is the mechanism; ``test_design`` is the machine-readable
 * commitment to how it could be wrong. A hypothesis without the latter cannot
 * be tested and is therefore not a hypothesis — M5 has nothing to route on and
 * M1 has nothing to re-probe.
 */
export interface HypothesisWire {
  /**
   * Stable id. Never slugify the statement and assume uniqueness.
   */
  id: string;
  /**
   * Technical mechanism claim.
   */
  statement: string;
  /**
   * The SAME claim in one everyday sentence, for a reader who runs evaluations and does no statistics. Not a second, softer claim — a second rendering of this one, checked host-side against a jargon list before it is accepted (see analysis.plain_language). Empty when the producer wrote none; a consumer should then show `statement` rather than paraphrase it into something the run never said.
   */
  plain_statement?: string;
  target_model: string;
  predicted_failure_mode: string;
  /**
   * Signal or contrast that would decide this, e.g. 'attention.image_token_ratio' or 'prompt_contrast describe_first'. M5 routes on it; M1 re-probes on it. EMPTY means the judge proposed none — see `is_routable`.
   */
  test_design?: string;
  status?: HypothesisStatus;
  /**
   * Set when mutated from an earlier hypothesis.
   */
  parent_id?: string | null;
  metadata?: { [key: string]: unknown };
}

/**
 * Health of one ``sample_id`` <-> ``FailureCase.id`` join.
 *
 * This exists because a broken join and a real null result are indistinguishable
 * downstream: unmatched ids are skipped, both groups come out empty, and the
 * tool reports "no significant association" — the same output as a model with
 * no defect. Emitting coverage makes "the pipeline is broken" a separate,
 * visible state from "the model is fine".
 */
export interface JoinReport {
  /**
   * e.g. 'attention.findings.per_case'
   */
  left: string;
  /**
   * e.g. 'CaseBatch(explore)'
   */
  right: string;
  n_left: number;
  n_right: number;
  n_matched: number;
  /**
   * n_matched / n_left
   */
  coverage: number;
  /**
   * First few unmatched ids, for triage.
   */
  unmatched_sample?: (string)[];
}

/**
 * A repair or intervention, as an embeddable diagram plus plain language.
 */
export interface MethodologyWire {
  title: string;
  /**
   * Two or three sentences a non-specialist can follow. Not the code.
   */
  summary?: string;
  /**
   * L1..L4 for a fix; empty for an intervention.
   */
  tier?: string;
  /**
   * Uncompressed mxfile document, embeddable as-is. Compressed diagrams are rejected: they cannot be diffed, reviewed, or repaired by hand.
   */
  drawio_xml: string;
  /**
   * Model calls this method makes per case. A large claimed gain alongside few model calls is the shape of a model-independent result, where the scaffold rather than the model did the work.
   */
  n_model_calls?: number | null;
}

/**
 * Identity + declared capabilities of the model under diagnosis.
 *
 * ``modalities`` is a SET, matched by subset against each analyzer's
 * ``applies_to_modalities``. Adding a modality adds one member here, not a new
 * combination type.
 */
export interface ModelRef {
  /**
   * What to call this model on a screen — a spec key or a product name, e.g. 'qwen3.5-2b' or 'VideoLLaMA2.1-7B-AV'.
   */
  name: string;
  backend?: string | null;
  modalities?: ("text" | "image" | "audio" | "video")[];
  /**
   * e.g. GENERATE / LOGPROBS / ATTENTION / HIDDEN_STATES.
   */
  capabilities?: (string)[];
  params?: { [key: string]: unknown };
}

/**
 * One measurement row. THE contract of the whole pipeline.
 *
 * Only ``sample_id`` is fixed. Every other key is analyzer-defined; any key
 * whose value is a finite number or bool is automatically harvested as a signal
 * named ``"<analyzer>.<key>"``. Non-numeric values are carried for display and
 * ignored by the statistics.
 */
export interface PerCaseRow {
  /**
   * Must equal FailureCaseWire.id. No fuzzy matching.
   */
  sample_id: string;
  /** Producer-defined keys. The envelope is closed; payload areas are not. */
  [key: string]: unknown;
}

/**
 * The user's natural-language statement of what to investigate.
 *
 * Carried through to M2 (tool selection), M3 (prompt) and M5 (the
 * protocol-consistency gate) — a hypothesis can be statistically real and still
 * be off-topic, and only this makes that judgeable.
 */
export interface ProtocolWire {
  description: string;
  task_domain?: string | null;
  probe_hints?: (string)[];
  /** Producer-defined keys. The envelope is closed; payload areas are not. */
  [key: string]: unknown;
}

/**
 * One analyzer's serialized output — the content of
 * ``artifacts/c<cycle>_<analyzer>.result.json``.
 *
 * Note what is NOT here: ``Result.artifacts`` (tensors, attention maps) never
 * goes inline. It is referenced through ``artifact_paths`` so a browser is
 * never asked to parse a ``.npy``.
 */
export interface ResultWire {
  /**
   * Registered analyzer name. Becomes the signal prefix.
   */
  analyzer: string;
  model: string;
  n_cases: number;
  findings?: FindingsWire;
  /**
   * metric -> what it measures, in one plain sentence, from the analyzer that produced it. The analyzer is the only thing that knows; every reader downstream was otherwise guessing from the identifier, and guessing produced chart labels no one could read. A metric absent here is undocumented — report it as such, do not paraphrase the name.
   */
  signal_docs?: { [key: string]: string };
  /**
   * Heavy outputs, by artifact key.
   */
  artifact_paths?: { [key: string]: ArtifactRef };
  metadata?: { [key: string]: unknown };
}

/**
 * Per-stage UI state. A single generic "N/A" loses information the reader
 * needs — in particular ``EMPTY`` (ran, produced nothing) and ``FAILED``
 * (did not run correctly) must never render the same.
 */
export type StageState = "not_started" | "running" | "succeeded" | "empty" | "abstained" | "partial" | "failed" | "skipped" | "unavailable";

/**
 * Terminal state of one stage in one cycle.
 *
 * ``EMPTY`` and ``ABSTAINED`` are successes with nothing to show; ``FAILED``
 * and ``UNAVAILABLE`` are not. Collapsing them loses the only signal a reader
 * has for whether to trust the absence of a result.
 */
export interface StageStatus {
  stage: "pre_m1" | "m1" | "explore" | "m2" | "m3" | "m4_surgery" | "m4_fix" | "m5";
  state: StageState;
  /**
   * Normal cycles start at 0; the post-loop fix uses -1.
   */
  cycle: number;
  /**
   * Why, for any state that is not plain success — the skip rule, the error, the reason for abstaining. One field, because a reader wants one answer.
   */
  reason?: string | null;
  duration_sec?: number | null;
  joins?: (JoinReport)[];
}

/**
 * One statistical test's verdict.
 *
 * ``reject`` is the RAW, uncorrected decision and must never drive a verdict on
 * its own. ``fdr_corrected`` is the family-level decision after multiplicity
 * control and is the only field a downstream verdict may read. They are kept as
 * separate fields precisely because collapsing them once let a p=0.14 result on
 * n=3 "support" a hypothesis.
 */
export interface StatsToolResultWire {
  /**
   * e.g. signal_label_assoc / mcnemar_evalue / bootstrap_diff / rank_corr
   */
  tool: string;
  /**
   * WHAT this result is about, in words, and unique within the report — the label a chart axis or a table row should carry.
   *
   * `tool` is the procedure, not the subject, and using it as a label put two rows reading 'Mcnemar evalue' on a chart with no way to tell them apart. `config['signal']` is the subject but is a machine name, and is absent on paired tools entirely. Neither can label a row on its own, so the producer states the label here.
   */
  measured?: string | null;
  /**
   * What the measured quantity IS, in one sentence, taken from the producing analyzer's `signal_docs`. Null means the analyzer did not document that metric — render it as undocumented rather than inventing a gloss, because a plausible wrong explanation of a statistic is worse than an admitted missing one.
   */
  means?: string | null;
  /**
   * Includes 'signal' — the routing key.
   */
  config?: { [key: string]: unknown };
  ok: boolean;
  error?: string | null;
  effect?: number | null;
  ci?: [number, number] | null;
  p_value?: number | null;
  e_value?: number | null;
  underpowered?: boolean;
  /**
   * RAW per-test decision. Not a verdict.
   */
  reject?: boolean;
  /**
   * Family-level decision after correction. None = correction not yet run (deferred descriptive phase) — which is NOT the same as False.
   */
  fdr_corrected?: boolean | null;
  /**
   * e.g. 'bh' / 'ebh'.
   */
  correction_method?: string | null;
  correction_family?: string | null;
  /**
   * Stable per-result key, e.g. 'signal_label_assoc:attention.entropy'. Required for correction: one tool NAME covers many tests.
   */
  analysis_key?: string | null;
  /**
   * Pre-correction decision, kept for audit alongside `reject`.
   */
  raw_reject?: boolean | null;
  figure_path?: string | null;
  /**
   * Cases in the signal-present group.
   */
  n_signal?: number | null;
  /**
   * Cases in the signal-absent group.
   */
  n_control?: number | null;
  /**
   * Cases the producing analyzer actually measured. Analyzers measure every case unless capped (an analyzer's max_cases or the probe agent's max_cases_per_analyzer), so compare this with the batch size.
   */
  n_measured?: number | null;
  /**
   * Labeled cases with no measurement that were counted as signal-ABSENT. Valid for a genuinely sparse flag that only lists where it fired; invalid when the analyzer simply never looked. Nothing in the value distinguishes the two, so the count must travel with the result.
   */
  n_imputed_absent?: number | null;
  summary?: string;
  /**
   * fail rates / permutation_p / CI internals / ...
   */
  details?: { [key: string]: unknown };
}

/**
 * The statistics behind one verdict, with its provenance.
 */
export interface TestEvidence {
  source?: "m2_stats_results" | "fallback_per_case" | "none";
  chosen_tool?: string | null;
  /**
   * How test_design resolved to this result.
   */
  routed_by?: string;
  consulted_tools?: (string)[];
  ci?: [number, number] | null;
  e_value?: number | null;
  /**
   * The field that actually decided this.
   */
  fdr_corrected?: boolean | null;
  underpowered?: boolean;
  n_signal?: number | null;
  n_control?: number | null;
  fail_rate_signal?: number | null;
  fail_rate_control?: number | null;
  details?: { [key: string]: unknown };
}

/**
 * M2 needs BOTH halves of the join: M1's numbers and the cases' labels.
 *
 * ``data`` is not optional in practice — without labels there is nothing to
 * correlate against and M2 degrades to threshold rules only.
 */
export interface AnalysisInput {
  /**
   * Path to the M1 ProbeOutput this analyzes.
   */
  results_ref: string;
  data: CaseBatchRef;
  model_name: string;
  protocol?: ProtocolWire | null;
  /**
   * False defers the e-BH validity verdict to the confirm phase; the report then carries effect sizes and charts but NO reject decision.
   */
  confirmatory?: boolean;
}

/**
 * M3 reads M2's report — both the numbers and the narrative.
 */
export interface DiagnosisInput {
  /**
   * Path to the M2 StatsReportWire.
   */
  analysis_ref: string;
  /**
   * Summaries of earlier cycles, so the judge avoids re-proposing.
   */
  prior_cycles?: ({ [key: string]: unknown })[];
  explore_context?: ExploreContextWire | null;
  /**
   * Descriptive-only clustering tags.
   */
  failure_modes?: (string)[];
}

/**
 * M3's serialized output: the hypotheses, and nothing that is already on disk.
 *
 * Zero hypotheses is a completed, empty result (state EMPTY or ABSTAINED) — not
 * an error. Rendering it red teaches readers to distrust a correct abstention.
 *
 * Judge I/O is deliberately absent. M3 is the one stage an LLM writes the
 * payload for, so its prompt and verbatim response do have to be recoverable —
 * but they are already persisted per cycle as
 * ``prompts/c<cycle>_m3_diagnosis.{prompt,response}.txt``, and the findings the
 * judge was shown are the M2 report named by :attr:`DiagnosisInput.analysis_ref`.
 * Carrying either inline here would be a second copy that can disagree with the
 * first.
 */
export interface DiagnosisOutput {
  schema_version?: number;
  /**
   * Run-level correlation id.
   */
  trace_id: string;
  /**
   * e.g. 'c0.m1'.
   */
  span_id?: string | null;
  cycle?: number;
  /**
   * ISO-8601 UTC.
   */
  produced_at: string;
  status: StageStatus;
  hypotheses?: (HypothesisWire)[];
}

/**
 * Repairs are attempted only on hypotheses M5 verified. ``max_tier`` bounds
 * how invasive the search may get and is the caller's decision, never the
 * agent's.
 */
export interface FixInput {
  hypothesis_ids: (string)[];
  data: CaseBatchRef;
  model_name: string;
  /**
   * L0 runtime config / L1 prompt / L2 scaffold / L3a internals-read / L3b internals-write / L4 params.
   *
   * L0 is in this list because `FixTier` has it — decoding settings are a real, and the least invasive, place to intervene. Omitting it made a tier the pipeline can produce unrepresentable.
   */
  max_tier: "L0" | "L1" | "L2" | "L3a" | "L3b" | "L4";
  /**
   * Feedback-driven propose->validate rounds. 1 = no loop.
   */
  max_repair_rounds?: number;
  prior_attempts_ref?: string | null;
}

/**
 * ``FixAgent.propose_and_validate`` result.
 *
 * What each candidate literally applied — the prompt text, the generated code —
 * is not here. It is the ``result.json`` under ``trial_root``, which is also
 * where the per-case outputs and the execution record sit; inlining a code blob
 * would put a second, drifting copy in every report a reader loads.
 */
export interface FixOutput {
  schema_version?: number;
  /**
   * Run-level correlation id.
   */
  trace_id: string;
  /**
   * e.g. 'c0.m1'.
   */
  span_id?: string | null;
  cycle?: number;
  /**
   * ISO-8601 UTC.
   */
  produced_at: string;
  status: StageStatus;
  max_tier: "L0" | "L1" | "L2" | "L3a" | "L3b" | "L4";
  /**
   * Which hypothesis went to which tier, and why.
   */
  routed?: ({ [key: string]: string })[];
  /**
   * The CONFIRMATION evidence: candidates validated on the held-out split. With a confirm split in play this is exactly one frozen candidate — selecting and testing on the same cases is the error the two-stage protocol exists to prevent.
   */
  attempted?: (FixAttemptWire)[];
  /**
   * The candidates tried while CHOOSING one, on the diagnosis split. Descriptive only — never confirmation evidence, and a reader must not add these effect sizes to the ones above.
   *
   * Carried because omitting it misrepresents the search: a run that tried seven candidates across L1 and L2 and confirmed one L1 reported a single L1 row, and every reader concluded L2 was never attempted. What was ruled out is part of what the run found — an `unsafe` candidate that repaired 7 cases and broke 8 is a result.
   */
  selection?: (FixAttemptWire)[];
  /**
   * Which candidate the selection phase froze for confirmation. Names a row in `selection`; `best` names one in `attempted`.
   */
  selected_on_explore?: string | null;
  /**
   * Winning candidate NAME. The row itself is in `attempted`.
   */
  best?: string | null;
  fixed?: boolean;
  /**
   * Candidate names surviving e-BH across the whole tested family. A winner must be BOTH individually `fixed` AND in this set — best-of-N needs its own correction.
   */
  ebh_survivors?: (string)[];
  repair_rounds?: number;
  /**
   * {recommend_tier, reason} when nothing validated. Escalation is NEVER automatic.
   */
  recommendation?: { [key: string]: unknown } | null;
  /**
   * Set when a candidate helped one subset and hurt another — evidence the hypothesis should be re-scoped, not that no fix exists. Feedback edge back into M3.
   */
  refine_signal?: { [key: string]: unknown } | null;
}

/**
 * M5's inputs.
 *
 * ``split`` is recorded because it changes what the verdict MEANS: testing on
 * the same cases the hypotheses were generated from is an internal consistency
 * check, not out-of-sample evidence. A reader cannot infer this from the numbers
 * and must not be left to guess.
 */
export interface HypothesisTestInput {
  /**
   * Path to the M3 DiagnosisOutput.
   */
  hypotheses_ref: string;
  /**
   * Path to the M2 StatsReportWire (post-correction).
   */
  stats_report_ref: string;
  data: CaseBatchRef;
  /**
   * None => every hypothesis is assumed protocol-consistent.
   */
  protocol?: ProtocolWire | null;
  /**
   * Which partition M5 actually ran on. 'explore' means the hypotheses were generated on these same cases — an in-sample adjudication, not held-out.
   */
  split?: "explore" | "confirm" | "all";
  alpha?: number;
}

/**
 * M5's serialized output — one result per hypothesis, plus the loop gate.
 */
export interface HypothesisTestOutput {
  schema_version?: number;
  /**
   * Run-level correlation id.
   */
  trace_id: string;
  /**
   * e.g. 'c0.m1'.
   */
  span_id?: string | null;
  cycle?: number;
  /**
   * ISO-8601 UTC.
   */
  produced_at: string;
  status: StageStatus;
  split?: "explore" | "confirm" | "all";
  results?: (HypothesisTestResultWire)[];
  /**
   * Whether the loop may stop on this cycle's evidence. Not simply `verified() != []` — the depth-tiered rule also weighs evidence grade.
   */
  stopping_criteria_met?: boolean;
}

/**
 * ``SurgeryAgent.operate`` result — causal evidence, not a repair.
 *
 * ``fixed`` here means "the intervention completely separated failing from
 * passing cases", i.e. the mechanism is confirmed. It does NOT mean a usable
 * repair exists; that claim belongs to :class:`FixOutput` alone.
 */
export interface InterventionOutput {
  schema_version?: number;
  /**
   * Run-level correlation id.
   */
  trace_id: string;
  /**
   * e.g. 'c0.m1'.
   */
  span_id?: string | null;
  cycle?: number;
  /**
   * ISO-8601 UTC.
   */
  produced_at: string;
  status: StageStatus;
  /**
   * Points into the M3 DiagnosisOutput.
   */
  hypothesis_id: string;
  /**
   * Verdict on the hypothesis. Named apart from the envelope's `status`, which is this STAGE's execution state — they answer different questions.
   */
  hypothesis_status: HypothesisStatus;
  strategy?: "verify_fn" | "analyzer_params" | "experiment_writer" | "passive_correlation";
  /**
   * Mechanism fully separates the groups. NOT a shippable repair.
   */
  fixed?: boolean;
  confidence_score?: number;
  /**
   * Breakdown: evidence gap / sample adequacy / control cleanliness.
   */
  evidence_dimensions?: { [key: string]: number };
  evidence?: { [key: string]: unknown };
  /**
   * The manipulation performed: which variable was changed, what was held fixed, what was compared. This is what makes the causal claim auditable.
   */
  methodology?: MethodologyWire | null;
  /**
   * Attempt folder when the experiment-writer strategy ran: generated code, stdout/stderr, workspace and record all sit there.
   */
  trial_root?: string | null;
  /**
   * When SUPPORTED: the cases NOT in the signal group — the refined subset for the next M1 cycle. null means no refinement, which differs from an empty batch.
   */
  new_data?: CaseBatchRef | null;
}

/**
 * Everything M1 needs. Cases are referenced, not inlined — a batch is large
 * and is already persisted.
 */
export interface ProbeInput {
  model: ModelRef;
  data: CaseBatchRef;
  protocol?: ProtocolWire | null;
  /**
   * Hypothesis ids from earlier cycles, for focused re-probing.
   */
  prior_hypotheses?: (string)[];
  /**
   * Failure-mode tags used by the no-judge fallback selector.
   */
  hint_failure_modes?: (string)[];
}

/**
 * M1's serialized output.
 *
 * Keyed by analyzer name because downstream routes BY name: M3 writes
 * ``test_design="attention.image_token_ratio"`` and M5 resolves it against this
 * map. A list would make that a scan and would not enforce uniqueness.
 */
export interface ProbeOutput {
  schema_version?: number;
  /**
   * Run-level correlation id.
   */
  trace_id: string;
  /**
   * e.g. 'c0.m1'.
   */
  span_id?: string | null;
  cycle?: number;
  /**
   * ISO-8601 UTC.
   */
  produced_at: string;
  status: StageStatus;
  /**
   * Who was diagnosed. Carried on the OUTPUT, not only on ProbeInput: a reader opens this file with no input beside it, and the only identity here used to be `ResultWire.model`, a repr — so the answer to 'which model is this report about' was a memory address.
   */
  model?: ModelRef | null;
  results?: { [key: string]: ResultWire };
  selection?: AnalyzerSelection;
  /**
   * analyzer -> error. Some failed + some succeeded = PARTIAL, not FAILED.
   */
  failed_analyzers?: { [key: string]: string };
}

/**
 * Seeds plus a budget. The search anchors both regime trees on the seeds.
 */
export interface ProbeSearchInput {
  model: ModelRef;
  seed_pool: CaseBatchRef;
  protocol?: ProtocolWire | null;
  /**
   * Total simulations (T_max).
   */
  budget?: number;
  /**
   * UCB exploration constant.
   */
  beta?: number;
  /**
   * Max children before progressive widening.
   */
  w_max?: number;
}

/**
 * Discovered cases plus search accounting.
 *
 * ``all_cases`` — not ``failure_cases`` — is what M1 should normally receive:
 * a batch of nothing but FAILs has no control group, and every downstream
 * comparison degenerates.
 *
 * The in-memory result also holds ``macro_root`` / ``micro_root``, two trees
 * whose nodes point at both parent and children. That graph is cyclic and
 * cannot be serialized naively, which is why the search trajectory is carried
 * here as an explicit flat edge list rather than a nested object.
 */
export interface ProbeSearchOutput {
  schema_version?: number;
  /**
   * Run-level correlation id.
   */
  trace_id: string;
  /**
   * e.g. 'c0.m1'.
   */
  span_id?: string | null;
  cycle?: number;
  /**
   * ISO-8601 UTC.
   */
  produced_at: string;
  status: StageStatus;
  n_simulations: number;
  n_macro: number;
  n_micro: number;
  /**
   * Every evaluated case, PASS and FAIL. Feed this to M1.
   */
  all_cases: CaseBatchRef;
  /**
   * The FAIL subset. Feed this to cluster_failures.
   */
  failure_cases: CaseBatchRef;
}

/**
 * M2's serialized report.
 *
 * Two field groups with different authority: everything above
 * ``descriptive_only`` is computed by code and is authoritative; ``conclusion``
 * and ``evidence_chain`` are written by the judge and are presentation only.
 * Empty narrative is valid and must never be backfilled with an invented
 * summary. The LLM may not write a number, and keeping the groups visibly
 * apart is what makes that reviewable.
 *
 * Absent by design: the judge's prompt and raw response (already
 * ``prompts/c<cycle>_m2_analysis.{prompt,response}.txt``), the tool-selection
 * plan (already ``artifacts/c<cycle>_m2_stats_plan.json``), the model name and
 * protocol (both in the run config and in :class:`AnalysisInput`), and the
 * threshold-rule narrative (a rendering of ``findings``).
 */
export interface StatsReportWire {
  schema_version?: number;
  /**
   * Run-level correlation id.
   */
  trace_id: string;
  /**
   * e.g. 'c0.m1'.
   */
  span_id?: string | null;
  cycle?: number;
  /**
   * ISO-8601 UTC.
   */
  produced_at: string;
  status: StageStatus;
  findings?: (AnalysisFindingWire)[];
  stats_tool?: "threshold_rules" | "llm_guided" | "selected_tools" | "generated";
  stats_results?: (StatsToolResultWire)[] | ExternalRef;
  corrected_rejections?: CorrectedRejections | ExternalRef;
  figures?: (ArtifactRef)[];
  /**
   * True = effect sizes and charts only, e-BH deferred. A reader MUST NOT render supported/rejected language while this is true.
   */
  descriptive_only?: boolean;
  /**
   * Judge-written. Presentation only.
   */
  conclusion?: string;
  /**
   * Judge-written derivation.
   */
  evidence_chain?: (string)[];
  /**
   * Non-empty only when the judge path was attempted AND raised. Not recoverable from the prompt files: a fallback still writes both of them.
   */
  llm_fallback_reason?: string;
  /**
   * Path to the M1 ProbeOutput. The in-memory report carries the Result objects themselves, but to_dict() drops them — M4/M5 still need per-case signals, so the serialized contract carries a reference instead of pretending they survive.
   */
  raw_results_ref?: string | null;
  /**
   * Signal<->label join health. Zero coverage is a plumbing failure.
   */
  joins?: (JoinReport)[];
}

/**
 * One hypothesis at a time. Surgery is per-claim by construction.
 */
export interface SurgeryInput {
  hypothesis_id: string;
  /**
   * Path to the M1 ProbeOutput, for per-case signal extraction.
   */
  results_ref: string;
  data: CaseBatchRef;
  model_name: string;
}

